### ISSUE TITLE
(BUG) (	 BPInfo VERSION 2.0.5 ) The application crashes when I click the test notification

### ISSUE THREAD

**Issue by friendsmobile** [ofalvai/BPInfo#1]
# Project Information

* Repository: https://github.com/ofalvai/BPInfo
* Project Name: BPInfo
* My Github Account: https://github.com/friendsmobile
* Download the application: [Here](https://play.google.com/store/apps/details?id=com.ofalvai.bpinfo)

# Expected behavior

When I click on the test notification, the application should not be crashed, the BIL test should be heard.

# Actual behavior
The application crashes when I click the test notification

# How to reproduce

* open the application
* click on ball icon 
* at the top right side click the 3 vertical dots
* and then click on the Test Notification option 
* Note the Error

* Browser/App version: 2.0.5
* Operating system: 6.0

# Recording Of The Bug

![20190707_125951](https://user-images.githubusercontent.com/51118734/60765696-2da49000-a053-11e9-91fb-ab48f9898b2f.gif)

# Logcat

<pre><code>E/AndroidRuntime( 9728): FATAL EXCEPTION: main

E/AndroidRuntime( 9728): Process: com.ofalvai.bpinfo, PID: 9728

E/AndroidRuntime( 9728): android.app.RemoteServiceException: Bad notification posted from package com.ofalvai.bpinfo: Couldn't create icon: StatusBarIcon(pkg=com.ofalvai.bpinfouser=0 id=0x7f080080 level=0 visible=true num=0 )

E/AndroidRuntime( 9728): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)

E/AndroidRuntime( 9728): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime( 9728): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime( 9728): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime( 9728): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime( 9728): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime( 9728): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime( 9728): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by ofalvai** [comment]
Thanks for the bug report, I'll look into it. What device were you using when the crash happened?

**Comment by friendsmobile** [comment]
i am using a samsung device j7

**Comment by ofalvai** [comment]
I couldn't reproduce the crash on any of my devices, and I haven't seen this crash in Crashlytics ever. So I guess this is a device specific bug, and I can't do too much about it.
